// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce_backend.Database;

#nullable disable

namespace eCommerce_backend.Migrations
{
    [DbContext(typeof(FootwearDbContext))]
    [Migration("20250819222351_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCommerce_backend.Models.Footwear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Footwear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Color = "White",
                            Description = "Classic Nike Air Max 90 in white.",
                            ImageUrl = "https://example.com/nike-airmax90-white.jpg",
                            Name = "Air Max 90",
                            Price = 129.99m,
                            Size = "42",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Color = "Black",
                            Description = "Adidas Ultraboost 22 for running and comfort.",
                            ImageUrl = "https://example.com/adidas-ultraboost22-black.jpg",
                            Name = "Ultraboost 22",
                            Price = 149.99m,
                            Size = "43",
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Converse",
                            Color = "Red",
                            Description = "Converse Chuck Taylor All Star classic sneakers.",
                            ImageUrl = "https://example.com/converse-chucktaylor-red.jpg",
                            Name = "Chuck Taylor All Star",
                            Price = 69.99m,
                            Size = "41",
                            Stock = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
